# Generated by Django 5.0.6 on 2024-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='book_image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
